# Generated by Django 5.0.1 on 2024-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_category_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
