# Generated by Django 5.0.1 on 2024-02-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
