# Generated by Django 5.0.1 on 2024-02-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='null', null=True, upload_to='productos'),
        ),
    ]
