# Generated by Django 5.0.1 on 2024-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovermail',
            name='password',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
